
---
- name: "configuration play."
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    ansible_host_key_checking: false
    ansible_stdout_callback: yaml
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  roles:
    - deploy
